# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn package -Dmaven.test.skip=true

    # Rename the JAR file
    - name: Rename JAR
      run: |
        tag=${GITHUB_REF##*/}
        mv target/*.jar target/go-rest-server-openapi-generator-${tag}.jar

    # Archive the JAR as an artifact
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-rest-server-openapi-generator-${{ github.ref_name }}
        path: target/go-rest-server-openapi-generator-${{ github.ref_name }}.jar
